apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-hands-on-kubernetes
spec:
  title: Hands on Kubernetes
  description: A collection of workshops which introduces Kubernetes concepts
  vendor: eduk8s.io
  difficulty: beginner
  url: https://github.com/eduk8s-labs/hands-on-kubernetes
  content:
    files: github.com/eduk8s-labs/hands-on-kubernetes
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
